package pack1;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MembEditUI.java
 *
 * Created on May 12, 2010, 2:33:36 PM
 */

/**
 *
 * @author xp_system
 */
public class STEditUI extends javax.swing.JFrame {

    /** Creates new form MembEditUI */
    public STEditUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdExit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        cmdUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        stst = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        stid = new javax.swing.JTextField();
        stvd = new javax.swing.JTextField();
        stag = new javax.swing.JTextField();
        stb = new javax.swing.JTextField();
        stad = new javax.swing.JTextField();
        stg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        stl = new javax.swing.JTextField();
        stnic = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sttp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        zcode = new javax.swing.JTextField();
        stf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Edition ");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        cmdExit.setText("Exit");
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });

        cmdUpdate.setText("Update");
        cmdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateActionPerformed(evt);
            }
        });

        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Select a Student");

        jButton1.setText("Back to manage student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Last Name");

        jLabel7.setText("First Name");

        jLabel14.setText("city");

        jLabel8.setText("Age");

        stc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stcActionPerformed(evt);
            }
        });

        jLabel10.setText("Address");

        jLabel15.setText("view date");

        stid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stidActionPerformed(evt);
            }
        });

        stag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stagActionPerformed(evt);
            }
        });

        stad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stadActionPerformed(evt);
            }
        });

        jLabel9.setText("Nic");

        stl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stlActionPerformed(evt);
            }
        });

        jLabel11.setText("Telephone Number");

        sttp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sttpActionPerformed(evt);
            }
        });

        jLabel1.setText("Student ID");

        jLabel3.setText("Birth Date");

        jLabel12.setText("zip code");

        jLabel4.setText("Gender");

        jLabel13.setText("state");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1053, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(cmdUpdate)
                        .addGap(58, 58, 58)
                        .addComponent(cmdExit)
                        .addGap(59, 59, 59)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(892, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addComponent(jLabel8)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15))
                    .addGap(103, 103, 103)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(stvd, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stc, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stst, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(zcode, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stid)
                        .addComponent(stb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stg, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stl, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stf, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stag, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stnic, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sttp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                    .addContainerGap(293, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdExit)
                    .addComponent(cmdUpdate)
                    .addComponent(jButton1))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(stid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(stb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(stg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(stl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(stf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(stad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(stnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(zcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(sttp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(stc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(stvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
         Statement stmt = null;
         Statement s2 = null;
         Statement s3 = null;
            ResultSet rs = null;
            ResultSet rs1 = null;
               ResultSet rs2 = null;
            String SQL = "SELECT * FROM student";
             String SQL1 = "SELECT * FROM contacts";
              String SQL2 = "SELECT * FROM statecode";

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_cmdExitActionPerformed

    private void cmdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateActionPerformed
        try {
           String userName = "Sa";//username of DB
            String password = "suba12345";//password of DB
            String url = "jdbc:sqlserver://localhost:1433;databaseName=stdacc";
                Connection con = DriverManager.getConnection(url,userName, password);
            stmt = con.createStatement();
             rs = stmt.executeQuery(SQL);
                 s2 = con.createStatement();
           
                rs1 = s2.executeQuery(SQL1);
 s3 = con.createStatement();
 rs2 = s3.executeQuery(SQL2);
            String vstid = stid.getText().trim();
            String vstl = stl.getText();
             String vstf = stf.getText();
            String vstag = stag.getText();
            String vstg = stg.getText();
            String vstnic = stnic.getText();
            String vstb = stb.getText();
            String vzcode = zcode.getText();
              String  vsttp= sttp.getText();
              String  vstad= stad.getText();
              String  vstst= stst.getText();
              String  vstc= stc.getText();
              
            // This is temporarily assigned same as membership date
          
           

            String strSQL = "Update student set LN ='"+(vstl)+"', FN = '"+ (vstf) +"', GENDER = '"+ (vstg) +"', AGE = '"+ (vstag) +"', NIC =' "+ (vstnic) +"' where ST_ID = '" + (vstid) + "';";
            int rowsEffected = stmt.executeUpdate(strSQL);
            if (rowsEffected == 0){
                JOptionPane.showMessageDialog(this, "Record does not exists");
            }else{
                JOptionPane.showMessageDialog(this,"Record modified");}
            
        String strSQL1 = "Update contacts set TP ='"+(vsttp)+"' where ST_ID =' " + (vstid) +"'; ";
            int rowsEffected1 = s2.executeUpdate(strSQL1);
            if (rowsEffected1 == 0){
                JOptionPane.showMessageDialog(this, "Record does not exists");}
            else
            { JOptionPane.showMessageDialog(this,"Record modified");}
        
        String strSQL2 = "Update statecode set STATE ='"+ (vstst) +"', ADDRESS = '"+ (vstad) +"', CITY = '"+ (vstc) +"' where Z_CODE = '" + (vzcode) +"'; ";
            int rowsEffected2 = s3.executeUpdate(strSQL2);
            if (rowsEffected2 == 0){
                JOptionPane.showMessageDialog(this, "Record does not exists");
            }else{
                JOptionPane.showMessageDialog(this,"Record modified");}
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_cmdUpdateActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // getSelectedValue() method extracts the current cursor location value into a variable
        String stid2 = (String) jList1.getSelectedValue();
        // Extract the first 4 characters as Member No into a variable
        String stid1 =stid2.trim().substring(0, 8);
        String vzcode1= stid2.trim().substring( stid2.trim().length() - 5);
        String query = "SELECT * FROM student WHERE ST_ID = '" + (stid1) + "';";
        String query2 = "SELECT * FROM contacts WHERE ST_ID = '" + (stid1) + "';";
         String query3 = "SELECT * FROM statecode WHERE Z_CODE = '" + (vzcode1) + "';";
        try {
                 String userName = "Sa";//username of DB
            String password = "suba12345";//password of DB
            String url = "jdbc:sqlserver://localhost:1433;databaseName=stdacc";
                Connection con = DriverManager.getConnection(url,userName, password);
            // Create SQL statement and execute query.
            stmt = con.createStatement();
       
            s2 = con.createStatement();
               s3 = con.createStatement();
            rs = stmt.executeQuery(query);
            rs1 = s2.executeQuery(query2);
             rs2 = s3.executeQuery(query3);  

            if (rs.next()) {

               String vstid = rs.getString("ST_ID");
                String vstb = rs.getString("B_DATE");
                String vstg = rs.getString("GENDER");
                String vstl = rs.getString("LN");
                String vstf = rs.getString("FN");
                String vstag = rs.getString("AGE");
                String vstnic = rs.getString("NIC");
                String vzcode = rs.getString("Z_CODE");
                String vstvd = rs.getString("VIEW_DATE");
                 
                // Displaying the contents in respective text boxes.
               
                stid.setText(vstid);
                stg.setText(vstg);
                stb.setText(vstb);
                stag.setText(vstag);
                stl.setText(vstl);
                stf.setText(vstf);
                
                zcode.setText(vzcode);
                stnic.setText(vstnic);
              
                stvd.setText(vstvd);
                
            } else {
                JOptionPane.showMessageDialog(null, "Record does not found in student table");
            }
            
            if (rs1.next()) {
            String vtp = rs1.getString("TP");
             sttp.setText(vtp);}
            else{JOptionPane.showMessageDialog(null, "Record does not found in contact table");}
              if (rs2.next()) {
            String vstst = rs2.getString("STATE");
             String vstc = rs2.getString("CITY");
             String vstad = rs2.getString("ADDRESS");
             stst.setText(vstst);
                stc.setText(vstc);
                stad.setText(vstad);
            }else {
                JOptionPane.showMessageDialog(null, "Record does not found in contacts table");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_jList1MouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       
     
        // Creating a ListModel object dModel to perform DefaultListModel
        // method operations
        DefaultListModel dModel = (DefaultListModel) jList1.getModel();
        // Method to add elements into jList1 control
        dModel.clear();
        try {
            String userName = "Sa";//username of DB
            String password = "suba12345";//password of DB
            String url = "jdbc:sqlserver://localhost:1433;databaseName=stdacc";
            Connection con = DriverManager.getConnection(url,userName, password);
            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL);
            while (rs.next()) {
                String stid = rs.getString("ST_ID");
                String SName = rs.getString("LN");
                   String vzcode = rs.getString("Z_CODE");
                // To make the Member no. as 4 digit because we will extract 4 digit from list value
		// in mouse click event.

                if (stid.length() < 4)
                {
                    int x = stid.length();
                    int nl = 4 - x;
                    while (nl > 0){
                        stid = stid + " ";
                        nl--;
                    }
                }
                dModel.addElement(stid + "- " + SName+ "- " +vzcode );
            }
            jList1.setModel(dModel);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new AddStudent().setVisible(true);

        this.dispose();   


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stcActionPerformed

    private void stidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stidActionPerformed

    private void stagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stagActionPerformed

    private void stadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stadActionPerformed

    private void sttpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sttpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sttpActionPerformed

    private void stlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stlActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STEditUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField stad;
    private javax.swing.JTextField stag;
    private javax.swing.JTextField stb;
    private javax.swing.JTextField stc;
    private javax.swing.JTextField stf;
    private javax.swing.JTextField stg;
    private javax.swing.JTextField stid;
    private javax.swing.JTextField stl;
    private javax.swing.JTextField stnic;
    private javax.swing.JTextField stst;
    private javax.swing.JTextField sttp;
    private javax.swing.JTextField stvd;
    private javax.swing.JTextField zcode;
    // End of variables declaration//GEN-END:variables

}
